sudo: required
services:
  - docker

before_install:
  - docker build -t antonioc74/react-test -f ./client/dockerfile.dev ./client 

script:
  - docker run antonioc74/react-test npm test -- --coverage

after_success:
  - docker build -t antonioc74/multi-client ./client
  - docker build -t antonioc74/multi-nginx ./nginx
  - docker build -t antonioc74/multi-server ./server
  - docker build -t antonioc74/multi-worker ./worker
  # login to docker cli 
  # Docker password and docker id are reated on docker profile page, these variable will hold the values.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take imgess and push them  to docker hub
  - docker push antonioc74/multi-client
  - docker push antonioc74/multi-nginx
  - docker push antonioc74/multi-server
  - docker push antonioc74/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-209160698439
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  