sudo: required
services:
  - docker

before_install:
  - docker build -t antonioc74/react-test -f ./client/dockerfile.dev ./client 

script:
  - docker build -t antonioc74/react-test npm test -- -- coverage

after_success:
  - docker build -t antonioc74/multi-client ./client
  - docker build -t antonioc74/multi-nginx ./nginx
  - docker build -t antonioc74/multi-server ./server
  - docker build -t antonioc74/multi-worker ./worker
  # login to docker cli 
  # Docker password and docker id are reated on docker profile page, these variable will hold the values.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take imgess and push them  to docker hub
  - docker push antonioc74/multi-client
  - docker push antonioc74/multi-nginx
  - docker push antonioc74/multi-server
  - docker push antonioc74/multi-worker

